version: "3"

services:

    pgadmin4:
        image: dpage/pgadmin4
        container_name: "pgadmin4"
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "root@email.com"
            PGADMIN_DEFAULT_PASSWORD: "root"
        ports:
            - "9001:80"
        depends_on:
            - db
        networks:
            - local
       
    db:
        image: postgres
        container_name: "pgsql"
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        networks:
            - local

  
networks:
  local:
    driver: bridge